### ISSUE TITLE
No Sound :(

### ISSUE THREAD

**Issue by dinu** [KOWLOR/DaftPunKonsole#18]
i downloaded this via codepen and i cant get the audio working. The warning shows you disabled it but any chance you an enable it back again ?

**Comment by hirako2000** [comment]
@dinugg (or whoever else need to know). All the sounds are here:
https://raw.githubusercontent.com/PwnzLPs/assets/master/daftpunkonsole

```
wget https://raw.githubusercontent.com/PwnzLPs/assets/master/daftpunkonsole/Ever3.mp3
```
Boom.
